repos:
- repo: https://github.com/andhikasamudra/pre-commit-golang
  rev: "1.0"
  hooks:
    - id: go-fmt
    - id: go-vet
    - id: go-imports
    - id: go-cyclo
    - id: validate-toml
    - id: no-go-testing
    - id: golangci-lint
    - id: go-critic
    - id: go-unit-tests
    - id: go-build
    - id: go-mod-tidy