version: "3.9"
services:
  api:
    build: .
    ports:
      - "3030:3030"
    environment:
      MYSQL_USER:  "root"
      MYSQL_PASSWORD : "root"
      MYSQL_HOST : "docker.for.mac.host.internal"
      MYSQL_PORT : "3306"
      MYSQL_DBNAME : "test_skyshi"