CREATE TABLE IF NOT EXISTS books
(
    id         INT GENERATED BY DEFAULT AS IDENTITY,
    guid       uuid                     default uuid_generate_v4() not null,
    title      text                                                not null,
    author     text                                                not null,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,

    primary key(id),
    unique(guid)
);
